### PR TITLE
fix: responsive for mobile devices

### PR DESCRIPTION
**Pull request by ihor-romaniuk**
### Description

This pull request contains minor style refactoring and fix for responsive in the LMS.

### Actual Result: 
Feedback is not fully displayed
| image |  image |
|---|---|

### Expected Result: 
Feedback is adaptive and fully displayed
| image | image |
|---|---|

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ihor-romaniuk! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by ihor-romaniuk** [comment]
Hello everyone,
It seems our pull request for the fix might be a bit stuck in the review process. Would someone be able to take a look at it when they have a moment?
Thank you so much for your time and help!

**Comment by mphilbrick211** [comment]
> Hello everyone, It seems our pull request for the fix might be a bit stuck in the review process. Would someone be able to take a look at it when they have a moment? Thank you so much for your time and help!

@openedx/axim-engineering

**Comment by feanil** [comment]
@mphilbrick211 I've asked @openedx/axim-aximprovements to take a look at this change.

**Review by irtazaakram — APPROVED** [review]
Tested it locally. LGTM 👍🏻

**Pull request merged**
